apiVersion: v1
kind: Pod
metadata:
  name: movie-details
  labels:
    app: movie-details
spec:
  containers:
  - name: movies
    image: movie-details-service:latest
    ports:
      - containerPort: 8000
    #imagePullPolicy: Never
    #resources:
  #    requests: {}
  #    limits:
  #      memory: "1024Mi"
  #      cpu: "1000m"
    imagePullPolicy: Never
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: moviedetailsservice
  labels:
    app: movie-details
spec:
  type: NodePort
  selector:
    app: movie-details
  ports:
  - name: tcp
    port: 8000
    targetPort: 8000
    nodePort: 30047
