apiVersion: v1
kind: Pod
metadata:
  name: imdb-movie-details
  labels:
    app: imdb-movie-details
spec:
  containers:
  - name: imdbmovies
    image: imdb-movie-details:latest
    ports:
      - containerPort: 8080
    #imagePullPolicy: Never
    #resources:
  #    requests: {}
  #    limits:
  #      memory: "1024Mi"
  #      cpu: "1000m"
    imagePullPolicy: Never
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 0

---
kind: Service 
apiVersion: v1
metadata:
  name: imdbmoviedetailsservice
  labels:
    app: imdb-movie-details
spec:
  type: NodePort
  selector:
    app: imdb-movie-details
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30046
